singleTypes:
  # fetches only the most recently updated entry in a particular content type
  # Generated file will be named after the fileName setting
  - id: homepage
    directory: /content/
    fileName: _index
    fileExtension: md

repeatableTypes:
  # fetches all the entries of a content type and places them in a directory.
  # Generated files will be named after their Entry ID in Contentful.

  # insights.
  - id: insight
    directory: /content/insights/
    fileExtension: md

  - id: author
    directory: /content/insights/authors/
    isHeadless: true
    fileExtension: md

  - id: insightCategory
    directory: /content/category/
    fileExtension: md

  # pages.
  - id: page
    directory: /content/
    fileExtension: md

  - id: section
    directory: /content/sections/
    fileExtension: md
    isHeadless: true

  - id: button
    directory: /content/buttons/
    fileExtension: md
    isHeadless: true

  # misc content.
  - id: chartCard
    directory: /content/chartCards/
    fileExtension: md
    isHeadless: true

  - id: chartExplorer
    directory: /content/chartExplorers/
    fileExtension: md
    isHeadless: true

  - id: html
    directory: /content/html/
    fileExtension: md
    isHeadless: true

  - id: linkCard
    directory: /content/linkCards/
    fileExtension: md
    isHeadless: true

  - id: testimonialCard
    directory: /content/testimonialCards/
    fileExtension: md
    isHeadless: true

  - id: icon
    directory: /content/icons/
    fileExtension: md
    isHeadless: true

  - id: faq
    directory: /content/faqs/
    fileExtension: md
    isHeadless: true

  - id: navbar
    directory: /content/navbar/
    fileExtension: md
    isHeadless: true

  - id: footer
    directory: /content/footer/
    fileExtension: md
    isHeadless: true

  - id: menu
    directory: /content/menus/
    fileExtension: md
    isHeadless: true

  - id: recentPosts
    directory: /content/recentPosts/
    fileExtension: md
    isHeadless: true
